/**
 * MDX Components.
 *
 * @remarks
 * Maps MDX elements to React components.
 *
 * @public
 */

import Image from "next/image";
import type { ComponentPropsWithoutRef } from "react";
import { highlight } from "sugar-high";
import { CodeBlockWrapper } from "@/src/components/mdx/code-block-wrapper";
import { MediaCompare } from "@/src/components/mdx/media-compare";
import { MediaGallery } from "@/src/components/mdx/media-gallery";
import { MediaImage } from "@/src/components/mdx/media-image";
import { MediaVideo } from "@/src/components/mdx/media-video";
import { Badge } from "@/src/components/ui/badge";
import { resolveAsset } from "@/src/lib/assets";
import { cn } from "@/src/lib/index";

const ARTICLE_FLOW_STYLE = {
	margin: 0,
	marginBottom: "1.5em",
	lineHeight: "var(--leading-article-body)",
	letterSpacing: "var(--tracking-article)",
} as const;

const ARTICLE_BLOCKQUOTE_STYLE = {
	margin: 0,
	marginTop: "var(--portfolio-space-section)",
	marginBottom: "var(--portfolio-space-section)",
	lineHeight: "var(--leading-article-quote)",
	letterSpacing: "var(--tracking-article)",
} as const;

// ═══════════════════════════════════════════════════════════════════════════
// COMPONENTS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * H1 - Article Title.
 */
export function H1({ className, ...props }: ComponentPropsWithoutRef<"h1">) {
	return (
		<h1
			className={cn("group relative", "font-medium", "text-foreground", className)}
			{...props}
		/>
	);
}

/**
 * H2 - Section Heading.
 */
export function H2({ className, ...props }: ComponentPropsWithoutRef<"h2">) {
	return (
		<h2
			className={cn("group relative", "font-medium", "text-foreground", className)}
			{...props}
		/>
	);
}

/**
 * H3 - Subsection Heading.
 */
export function H3({ className, ...props }: ComponentPropsWithoutRef<"h3">) {
	return (
		<h3
			className={cn("group relative", "font-semibold", "text-foreground", className)}
			{...props}
		/>
	);
}

/**
 * H4 - Minor Heading.
 */
export function H4({ className, ...props }: ComponentPropsWithoutRef<"h4">) {
	return (
		<h4
			className={cn("group relative", "font-semibold", "text-foreground", className)}
			{...props}
		/>
	);
}

/**
 * Paragraph - Body Text.
 */
export function P({ className, ...props }: ComponentPropsWithoutRef<"p">) {
	return (
		<p
			className={cn("portfolio-body-lg", "text-foreground", className)}
			style={ARTICLE_FLOW_STYLE}
			{...props}
		/>
	);
}

/**
 * Strong - Bold Text
 */
export function Strong({ className, ...props }: ComponentPropsWithoutRef<"strong">) {
	return <strong className={cn("font-bold", "text-foreground", className)} {...props} />;
}

/**
 * Emphasis - Italic Text
 */
export function Em({ className, ...props }: ComponentPropsWithoutRef<"em">) {
	return <em className={cn("italic", "text-foreground", className)} {...props} />;
}

/**
 * Anchor - Links
 */
export function A({ className, ...props }: ComponentPropsWithoutRef<"a">) {
	// Check if this is an anchor link generated by rehype-autolink-headings
	const isAnchor = className?.includes("anchor");

	if (isAnchor) {
		return (
			<a
				className={cn(
					"absolute top-1/2 -left-6 -translate-y-1/2 opacity-0 transition-opacity group-hover:opacity-100",
					"text-muted-foreground no-underline hover:text-foreground",
					className,
				)}
				{...props}
			/>
		);
	}

	return (
		<a
			className={cn(
				"font-medium underline underline-offset-4",
				"text-primary hover:text-primary-600",
				"transition-colors",
				className,
			)}
			{...props}
		/>
	);
}

/**
 * Unordered List
 */
export function UL({ className, ...props }: ComponentPropsWithoutRef<"ul">) {
	return (
		<ul
			className={cn(
				"portfolio-body-lg list-outside list-disc pl-6",
				"text-foreground",
				"marker:text-surface-500 dark:marker:text-surface-400",
				className,
			)}
			style={ARTICLE_FLOW_STYLE}
			{...props}
		/>
	);
}

/**
 * Ordered List
 */
export function OL({ className, ...props }: ComponentPropsWithoutRef<"ol">) {
	return (
		<ol
			className={cn(
				"portfolio-body-lg list-outside list-decimal pl-8",
				"text-foreground",
				"marker:font-mono marker:text-surface-500 dark:marker:text-surface-400",
				className,
			)}
			style={ARTICLE_FLOW_STYLE}
			{...props}
		/>
	);
}

/**
 * List Item
 */
export function LI({ className, ...props }: ComponentPropsWithoutRef<"li">) {
	return (
		<li
			className={cn("text-foreground", className)}
			style={{
				lineHeight: "var(--leading-article-body)",
				letterSpacing: "var(--tracking-article)",
			}}
			{...props}
		/>
	);
}

/**
 * Blockquote component.
 */
export function Blockquote({ className, ...props }: ComponentPropsWithoutRef<"blockquote">) {
	return (
		<blockquote
			className={cn(
				"border-surface-300 border-l pl-(--portfolio-space-group)",
				"text-surface-700 dark:border-surface-700 dark:text-surface-300",
				"portfolio-body-lg italic",
				className,
			)}
			style={ARTICLE_BLOCKQUOTE_STYLE}
			{...props}
		/>
	);
}

/**
 * Horizontal Rule.
 */
export function HR({ className, ...props }: ComponentPropsWithoutRef<"hr">) {
	return (
		<hr
			className={cn("border-surface-200 border-t dark:border-surface-800", className)}
			style={{
				margin: 0,
				marginTop: "var(--portfolio-space-section)",
				marginBottom: "var(--portfolio-space-section)",
			}}
			{...props}
		/>
	);
}

/**
 * Inline Code
 */
export function Code({ className, ...props }: ComponentPropsWithoutRef<"code">) {
	// Check if inside a <pre> (code block) - don't add inline styling
	const isInPre = className?.includes("language-");

	if (isInPre) {
		return <code className={className} {...props} />;
	}

	return (
		<code
			className={cn(
				"rounded-none bg-surface-100 px-1.5 py-0.5 font-mono text-[0.9em] leading-none",
				"text-surface-900 dark:bg-surface-900 dark:text-surface-50",
				className,
			)}
			{...props}
		/>
	);
}

import { isValidElement, type ReactElement } from "react";
import { MermaidDiagram } from "@/src/components/mdx/mermaid-diagram";

/**
 * Code Block (Pre).
 */
export function Pre({ className, children, ...props }: ComponentPropsWithoutRef<"pre">) {
	// 1. Mermaid Check
	if (isValidElement(children)) {
		const child = children as ReactElement<{ children?: string; className?: string }>;
		if (child.props?.className?.includes("language-mermaid")) {
			return <MermaidDiagram code={child.props.children || ""} />;
		}
	}

	// 2. Extract raw text from MDX children
	const extractText = (node: React.ReactNode): string => {
		if (typeof node === "string") return node;
		if (typeof node === "number") return node.toString();
		if (Array.isArray(node)) return node.map(extractText).join("");
		if (isValidElement(node)) {
			const element = node as ReactElement<{ children?: React.ReactNode }>;
			return extractText(element.props.children);
		}
		return "";
	};

	const rawCode = extractText(children);

	// 3. Highlight on the server
	const highlightedHtml = highlight(rawCode);

	return (
		<CodeBlockWrapper
			className={cn("mb-(--portfolio-space-group) w-full", className)}
			highlightedHtml={highlightedHtml}
			rawCode={rawCode}
			{...props}
		/>
	);
}

/**
 * Table Container
 */
export function Table({ className, ...props }: ComponentPropsWithoutRef<"table">) {
	return (
		<div
			data-breakout="true"
			className="media-breakout mb-(--portfolio-space-group) w-full overflow-x-auto"
		>
			<table className={cn("w-full border-collapse text-sm", className)} {...props} />
		</div>
	);
}

/**
 * Table Head
 */
export function THead({ className, ...props }: ComponentPropsWithoutRef<"thead">) {
	return (
		<thead
			className={cn("border-surface-200 border-b dark:border-surface-800", className)}
			{...props}
		/>
	);
}

/**
 * Table Body
 */
export function TBody({ className, ...props }: ComponentPropsWithoutRef<"tbody">) {
	return <tbody className={cn(className)} {...props} />;
}

/**
 * Table Row
 */
export function TR({ className, ...props }: ComponentPropsWithoutRef<"tr">) {
	return <tr className={cn("py-3 text-left align-bottom", className)} {...props} />;
}

/**
 * Table Header Cell
 */
export function TH({ className, ...props }: ComponentPropsWithoutRef<"th">) {
	return (
		<th
			className={cn(
				"py-3 text-left align-bottom",
				"font-medium font-mono text-xs uppercase tracking-widest",
				"text-surface-600 dark:text-surface-400",
				className,
			)}
			{...props}
		/>
	);
}

/**
 * Table Data Cell
 */
export function TD({ className, ...props }: ComponentPropsWithoutRef<"td">) {
	return <td className={cn("py-3 align-top text-foreground", className)} {...props} />;
}

/**
 * Img - Image component.
 */
export function Img({ className, alt, src, ...props }: ComponentPropsWithoutRef<"img">) {
	if (!src) return null;
	const resolvedSrc = resolveAsset(src as string);
	const isStatic = typeof resolvedSrc !== "string";

	return (
		<figure data-breakout="true" className="media-breakout mb-(--portfolio-space-group) w-full">
			<div
				className="relative w-full border border-surface-200 dark:border-surface-800"
				style={{
					aspectRatio:
						isStatic && resolvedSrc.width && resolvedSrc.height
							? `${resolvedSrc.width} / ${resolvedSrc.height}`
							: "16 / 9",
				}}
			>
				<Image
					src={resolvedSrc}
					alt={alt || ""}
					fill
					className={cn("object-cover", className)}
					placeholder={isStatic ? "blur" : "empty"}
					{...(props as Omit<React.ComponentProps<typeof Image>, "src" | "alt">)}
				/>
			</div>
			{alt && (
				<figcaption className="mt-(--portfolio-space-tight) text-left font-mono text-surface-500 text-xs dark:text-surface-400">
					{alt}
				</figcaption>
			)}
		</figure>
	);
}

// ═══════════════════════════════════════════════════════════════════════════
// COMPONENT MAP FOR MDX
// ═══════════════════════════════════════════════════════════════════════════

export const mdxComponents = {
	h1: H1,
	h2: H2,
	h3: H3,
	h4: H4,
	p: P,
	strong: Strong,
	em: Em,
	a: A,
	ul: UL,
	ol: OL,
	li: LI,
	blockquote: Blockquote,
	hr: HR,
	code: Code,
	pre: Pre,
	table: Table,
	thead: THead,
	tbody: TBody,
	tr: TR,
	th: TH,
	td: TD,
	img: Img,
	Badge, // Exposed to MDX
	// Media Components
	Image: MediaImage,
	Video: MediaVideo,
	Compare: MediaCompare,
	Gallery: MediaGallery,
};
