import type { ComponentPropsWithoutRef } from "react";
import { cn } from "@/src/lib/utils";
import { Badge } from "@/src/components/ui/badge";
import { CodeBlockWrapper } from "@/src/components/mdx/code-block-wrapper";

// ═══════════════════════════════════════════════════════════════════════════
// SWISS DESIGN MDX COMPONENTS
// Premium typography system matching MonolithCard, FloatingNav, and homepage
// ═══════════════════════════════════════════════════════════════════════════

/**
 * H1 - Page Title (rarely used in MDX content, handled by page wrapper)
 */
export function H1({ className, ...props }: ComponentPropsWithoutRef<"h1">) {
  return (
    <h1
      className={cn("mb-6 mt-0 text-heading-xl", "text-foreground", className)}
      {...props}
    />
  );
}

/**
 * H2 - Major Section Heading
 * Features bottom border separator (Swiss grid line aesthetic)
 */
export function H2({ className, ...props }: ComponentPropsWithoutRef<"h2">) {
  return (
    <h2
      className={cn(
        "mb-6 mt-16 first:mt-0",
        "text-2xl font-bold tracking-tight",
        "text-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * H3 - Subsection Heading
 */
export function H3({ className, ...props }: ComponentPropsWithoutRef<"h3">) {
  return (
    <h3
      className={cn(
        "mb-4 mt-12 first:mt-0",
        "text-xl font-bold tracking-tight",
        "text-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * H4 - Minor Heading
 */
export function H4({ className, ...props }: ComponentPropsWithoutRef<"h4">) {
  return (
    <h4
      className={cn(
        "mb-3 mt-8 first:mt-0",
        "text-lg font-bold",
        "text-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Paragraph - Body Text
 * Uses text-body-md for optimal readability
 */
export function P({ className, ...props }: ComponentPropsWithoutRef<"p">) {
  return (
    <p
      className={cn("mb-6 leading-relaxed", "text-muted-foreground", className)}
      {...props}
    />
  );
}

/**
 * Strong - Bold Text
 */
export function Strong({
  className,
  ...props
}: ComponentPropsWithoutRef<"strong">) {
  return (
    <strong
      className={cn("font-bold", "text-foreground", className)}
      {...props}
    />
  );
}

/**
 * Emphasis - Italic Text
 */
export function Em({ className, ...props }: ComponentPropsWithoutRef<"em">) {
  return (
    <em
      className={cn("italic", "text-muted-foreground", className)}
      {...props}
    />
  );
}

/**
 * Anchor - Links
 */
export function A({ className, ...props }: ComponentPropsWithoutRef<"a">) {
  // Check if this is an anchor link generated by rehype-autolink-headings
  const isAnchor = className?.includes("anchor");

  if (isAnchor) {
    return (
      <a
        className={cn(
          "ml-2 inline-block opacity-0 transition-opacity group-hover:opacity-100",
          "text-muted-foreground hover:text-foreground no-underline",
          className,
        )}
        {...props}
      />
    );
  }

  return (
    <a
      className={cn(
        "font-medium underline underline-offset-4",
        "text-primary hover:text-primary-600",
        "transition-colors",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Unordered List
 */
export function UL({ className, ...props }: ComponentPropsWithoutRef<"ul">) {
  return (
    <ul
      className={cn(
        "mb-6 ml-6 list-disc space-y-2",
        "text-muted-foreground",
        "marker:text-muted-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Ordered List
 */
export function OL({ className, ...props }: ComponentPropsWithoutRef<"ol">) {
  return (
    <ol
      className={cn(
        "mb-6 ml-6 list-decimal space-y-2",
        "text-muted-foreground",
        "marker:font-mono marker:text-muted-foreground",
        className,
      )}
      {...props}
    />
  );
}

/**
 * List Item
 */
export function LI({ className, ...props }: ComponentPropsWithoutRef<"li">) {
  return <li className={cn("leading-relaxed", className)} {...props} />;
}

/**
 * Blockquote - Callout Style
 * Left border accent, subtle background
 */
export function Blockquote({
  className,
  ...props
}: ComponentPropsWithoutRef<"blockquote">) {
  return (
    <blockquote
      className={cn(
        "relative mb-8 overflow-hidden rounded-none", // Strict Swiss (0px)
        // Border: Explicit contrast (not opacity-adjusted mid-grays)
        "border border-surface-950/15 dark:border-surface-50/15",
        // Glassmorphism: Matches FloatingNav precision
        "bg-white/80 dark:bg-surface-950/80 backdrop-blur-lg",
        "p-6 pl-8",
        "text-lg font-medium italic leading-relaxed",
        "text-surface-700 dark:text-surface-200",
        // Insignia Stripe: Foreground color (matches corner stamps)
        "before:absolute before:left-0 before:top-0 before:bottom-0 before:w-1",
        "before:bg-surface-950 dark:before:bg-surface-50",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Horizontal Rule - 'Silent Precision'
 * Swiss Design: Minimalist hairline separator. No noise.
 */
export function HR({ className, ...props }: ComponentPropsWithoutRef<"hr">) {
  return (
    <hr
      className={cn(
        "my-12 border-t border-surface-200 dark:border-surface-800",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Inline Code
 */
export function Code({
  className,
  ...props
}: ComponentPropsWithoutRef<"code">) {
  // Check if inside a <pre> (code block) - don't add inline styling
  const isInPre = className?.includes("language-");

  if (isInPre) {
    return <code className={className} {...props} />;
  }

  return (
    <code
      className={cn(
        "relative rounded-none px-[0.3rem] py-[0.15rem] font-mono text-[0.85em] font-medium",
        // Anti-gray: High contrast border + clear background
        "border border-surface-200 dark:border-surface-700",
        "bg-surface-50 dark:bg-surface-900",
        "text-surface-900 dark:text-surface-50",
        // Hover effect for interactivity
        "transition-colors duration-200 hover:border-surface-300 dark:hover:border-surface-600",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Code Block (Pre)
 * Sharp borders, dark theme, with copy button
 */
export function Pre({
  className,
  children,
  ...props
}: ComponentPropsWithoutRef<"pre">) {
  return (
    <CodeBlockWrapper className={className} {...props}>
      {children}
    </CodeBlockWrapper>
  );
}

/**
 * Table Container
 */
export function Table({
  className,
  ...props
}: ComponentPropsWithoutRef<"table">) {
  return (
    <div className="mb-8 overflow-x-auto">
      <table
        className={cn("w-full border-collapse text-sm", className)}
        {...props}
      />
    </div>
  );
}

/**
 * Table Head
 */
export function THead({
  className,
  ...props
}: ComponentPropsWithoutRef<"thead">) {
  return (
    <thead
      className={cn(
        // Swiss: No heavy bottom border, just spatial separation or very subtle line
        "border-b border-surface-200 dark:border-surface-800",
        className,
      )}
      {...props}
    />
  );
}

/**
 * Table Body
 */
export function TBody({
  className,
  ...props
}: ComponentPropsWithoutRef<"tbody">) {
  return (
    <tbody className={cn("divide-y divide-border", className)} {...props} />
  );
}

/**
 * Table Row
 */
export function TR({ className, ...props }: ComponentPropsWithoutRef<"tr">) {
  return (
    <tr
      className={cn(
        "group transition-all duration-200 ease-out",
        "hover:bg-surface-50 dark:hover:bg-surface-900", // Clean high-contrast hover
        className,
      )}
      {...props}
    />
  );
}

/**
 * Table Header Cell
 */
export function TH({ className, ...props }: ComponentPropsWithoutRef<"th">) {
  return (
    <th
      className={cn(
        "px-4 py-3 text-left align-middle",
        "font-mono text-xs font-bold uppercase tracking-widest", // More architectural tracking
        "text-surface-900 dark:text-surface-100", // High contrast headers
        // Swiss: Removed individual cell borders to avoid double-border clutter
        className,
      )}
      {...props}
    />
  );
}

/**
 * Table Data Cell
 */
export function TD({ className, ...props }: ComponentPropsWithoutRef<"td">) {
  return (
    <td
      className={cn("px-4 py-3", "text-muted-foreground", className)}
      {...props}
    />
  );
}

/**
 * Image - Next.js optimized (placeholder for now)
 */
export function Img({
  className,
  alt,
  ...props
}: ComponentPropsWithoutRef<"img">) {
  return (
    <figure className="mb-8">
      <img
        className={cn("w-full border-2", "border-border", className)}
        alt={alt || ""}
        {...props}
      />
      {alt && (
        <figcaption className="mt-3 text-center font-mono text-xs text-muted-foreground">
          {alt}
        </figcaption>
      )}
    </figure>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// COMPONENT MAP FOR MDX
// ═══════════════════════════════════════════════════════════════════════════

export const mdxComponents = {
  h1: H1,
  h2: H2,
  h3: H3,
  h4: H4,
  p: P,
  strong: Strong,
  em: Em,
  a: A,
  ul: UL,
  ol: OL,
  li: LI,
  blockquote: Blockquote,
  hr: HR,
  code: Code,
  pre: Pre,
  table: Table,
  thead: THead,
  tbody: TBody,
  tr: TR,
  th: TH,
  td: TD,
  img: Img,
  Badge, // Exposed to MDX
};
